feat: initial linked keywords additions
GlobalX/PockyBot.NET pull request #179
Opened 2021-12-17 05:30 UTC by ThomasGillin

resolves #177

2022-01-10 23:52 UTC, Evangelinexx approved these changes

2022-01-13 05:02 UTC, jimcullenaus requested changes
If I'm understanding what this is doing correctly, it looks pretty good! Just need to add some documentation explaining how it works in the README, and update the Help command to support it.

2022-01-13 10:24 UTC, ThomasGillin commented on src/PockyBot.NET/Services/Pegs/PegRequestValidator.cs
> +            var linkedKeywords = _configRepository.GetStringConfig("linkedKeyword").Select(x => x.Split(':'));
Yes. That's correct. I'll see if I can figure a way to simplify it.

2022-01-13 23:08 UTC, Chromadream approved these changes

2022-01-13 23:49 UTC, jimcullenaus approved these changes

2022-01-13 23:49 UTC, jimcullenaus commented on README.md
> +keywords for validation and results purposes.
nice!

2022-01-13 23:49 UTC, jimcullenaus commented on src/PockyBot.NET/Services/Triggers/Help.cs
> +                    $"    * Example 2: To add a linked keyword called \"awesome\" to the \"amazing\" keyword, type `@{_pockyBotSettings.BotName} {Commands.StringConfig} {ConfigActions.Add} linkedKeyw
looks good!

2022-01-14 01:55 UTC, AUSBird approved these changes

2022-01-20 05:26 UTC, jimcullenaus approved these changes

2022-01-28 02:46 UTC, Chromadream approved these changes

2022-01-28 02:55 UTC, Lauraducky approved these changes

2022-01-28 03:00 UTC, merged

2022-01-28 03:05 UTC, Lauraducky commented
:tada: This PR is included in version 1.14.0 :tada:

The release is available on:
- `v1.14.0`
- [GitHub release](https://github.com/GlobalX/PockyBot.NET/releases/tag/v1.14.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: