chore: add dependabot config
GlobalX/PockyBot.NET pull request #80
Opened 2020-09-23 05:51 UTC by Lauraducky

2020-09-23 05:52 UTC, Evangelinexx approved these changes

2020-09-23 05:59 UTC, jimcullenaus submitted a review, later dismissed

2020-09-23 05:59 UTC, Evangelinexx submitted a review, later dismissed

2020-09-23 06:02 UTC, Evangelinexx approved these changes

2020-09-23 06:08 UTC, jimcullenaus approved these changes

2020-09-23 06:09 UTC, jimcullenaus requested changes

2020-09-23 06:09 UTC, jimcullenaus commented on .github/dependabot.yml
> +  - drewfreyling
indentation is bad

2020-09-23 06:10 UTC, jimcullenaus approved these changes

2020-09-23 06:10 UTC, Evangelinexx approved these changes

2020-09-23 06:17 UTC, merged

2020-09-25 05:41 UTC, Lauraducky commented
:tada: This PR is included in version 1.13.2 :tada:

The release is available on:
- `v1.13.2`
- [GitHub release](https://github.com/GlobalX/PockyBot.NET/releases/tag/v1.13.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: